# Generated by Django 4.2.1 on 2023-05-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_alter_category_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
    ]
