# Generated by Django 4.2.1 on 2023-05-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_remove_category_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link_new',
            field=models.CharField(max_length=500, verbose_name='Ссылка на источник'),
        ),
    ]
