# Generated by Django 4.2.1 on 2023-05-19 05:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0006_alter_news_created_alter_news_updated_imagenews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenews',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_news.news', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 11, 37, 54, 4292), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 11, 37, 54, 4292), verbose_name='Дата обновления'),
        ),
    ]
