# Generated by Django 4.2.1 on 2023-05-22 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0010_alter_news_created_alter_news_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 15, 2, 23, 632269), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 15, 2, 23, 632269), verbose_name='Дата обновления'),
        ),
    ]
