# Generated by Django 4.2.1 on 2023-05-23 04:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0012_alter_news_created_alter_news_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cats', to='app_news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 10, 59, 11, 271567), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 10, 59, 11, 271567), verbose_name='Дата обновления'),
        ),
    ]
